Removed hard-coded path "/nhin/SUNAppserver" and replaced with $AS_HOME. Removed hard-coded path "/nhin/jdk/jdk1.6.0_18" and replaced with $JAVA_HOME Validate that $AS_HOME and $JAVA_HOME are present as environment variables - try to default both if either is present.  Throw error if no value set for $JAVA_HOME and also if /nhin/jdk/jdk1.7.0_02 folder does not exist. GATEWAY-739

diff --git a/Product/Install/GlassFish/templates/asenv.conf.template b/Product/Install/GlassFish/templates/asenv.conf.template
--- a/Product/Install/GlassFish/templates/asenv.conf.template
+++ b/Product/Install/GlassFish/templates/asenv.conf.template
@@ -3,26 +3,46 @@
 # Use is subject to license terms.
 #
 
-AS_ANT="/nhin/SUNWappserver/lib/ant"
-AS_ANT_LIB="/nhin/SUNWappserver/lib/ant/lib"
-AS_WEBSERVICES_LIB="/nhin/SUNWappserver/lib"
-AS_PERL="/nhin/SUNWappserver/lib/perl"
-AS_NSS="/nhin/SUNWappserver/lib"
-AS_NSS_BIN="/nhin/SUNWappserver/lib"
-AS_IMQ_LIB="/nhin/SUNWappserver/imq/lib"
-AS_IMQ_BIN="/nhin/SUNWappserver/imq/bin"
-AS_CONFIG="/nhin/SUNWappserver/config"
-AS_INSTALL="/nhin/SUNWappserver"
-AS_JAVA="/nhin/jdk/jdk1.6.0_16"
-AS_ACC_CONFIG="/nhin/SUNWappserver/domains/domain1/config/sun-acc.xml"
-AS_JHELP="/nhin/SUNWappserver/lib"
-AS_ICU_LIB="/nhin/SUNWappserver/lib"
-AS_DEF_DOMAINS_PATH="/nhin/SUNWappserver/domains"
-AS_JDMK_HOME="/nhin/SUNWappserver/lib/SUNWjdmk/5.1"
+#if AS_HOME is empty, set to default
+if [[ ${AS_HOME} = "" ]]
+then
+   export AS_ENV="/nhin/SUNWappserver"
+fi
+
+#if JAVA_HOME is empty, check to see if standard folder exists
+# if not, exit script
+STD_JAVA="/nhin/jdk/jdk1.7.0_02"
+if [[ ${JAVA_HOME} = "" ]]
+then
+   if [ -d $STD_JAVA ]
+   then
+      export JAVA_HOME=$STD_JAVA
+   else
+      echo "[ERROR]: JAVA_HOME: $STD_JAVA does not exist."
+      exit 1;
+   fi
+fi
+
+AS_ANT="$AS_HOME/lib/ant"
+AS_ANT_LIB="$AS_HOME/lib/ant/lib"
+AS_WEBSERVICES_LIB="$AS_HOME/lib"
+AS_PERL="$AS_HOME/lib/perl"
+AS_NSS="$AS_HOME/lib"
+AS_NSS_BIN="$AS_HOME/lib"
+AS_IMQ_LIB="$AS_HOME/imq/lib"
+AS_IMQ_BIN="$AS_HOME/imq/bin"
+AS_CONFIG="$AS_HOME/config"
+AS_INSTALL="$AS_HOME"
+AS_JAVA="$JAVA_HOME"
+AS_ACC_CONFIG="$AS_HOME/domains/domain1/config/sun-acc.xml"
+AS_JHELP="$AS_HOME/lib"
+AS_ICU_LIB="$AS_HOME/lib"
+AS_DEF_DOMAINS_PATH="$AS_HOME/domains"
+AS_JDMK_HOME="$AS_HOME/lib/SUNWjdmk/5.1"
 AS_NATIVE_LAUNCHER="false"
 AS_NATIVE_LAUNCHER_LIB_PREFIX="/jre/lib/i386/client"
-AS_WEBCONSOLE_LIB="/nhin/SUNWappserver/lib"
-AS_JATO_LIB="/nhin/SUNWappserver/lib"
+AS_WEBCONSOLE_LIB="$AS_HOME/lib"
+AS_JATO_LIB="$AS_HOME/lib"
 AS_HADB="Does not exist"
-AS_DERBY_INSTALL="/nhin/SUNWappserver/javadb"
+AS_DERBY_INSTALL="$AS_HOME/javadb"
 AS_MFWK_HOME="/opt/SUNWmfwk"
